"""empty message

Revision ID: 36dc911e0a7d
Revises: 4c52e3a40e28
Create Date: 2022-04-13 11:28:02.432380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36dc911e0a7d'
down_revision = '4c52e3a40e28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('medications', sa.Column('dosage', sa.String(length=100), nullable=True))
    op.add_column('medications', sa.Column('frequency', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('medications', 'frequency')
    op.drop_column('medications', 'dosage')
    # ### end Alembic commands ###
