"""empty message

Revision ID: dbf7119d8fd9
Revises: 8d0d89a56352
Create Date: 2022-04-09 19:14:20.329073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf7119d8fd9'
down_revision = '8d0d89a56352'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vaccines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vaccine', sa.String(length=100), nullable=True),
    sa.Column('last_shot', sa.DateTime(), nullable=True),
    sa.Column('next_shot', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vaccines')
    # ### end Alembic commands ###
